version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nbalive"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vh2regr54p5a"
s3_prefix = "nbalive"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

